#垂直分库
spring:
  shardingsphere:
    datasource:
      names: userdb0
      userdb0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3316/user_db?serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      tables:
        t_user:
          actual-data-nodes: userdb$->{0}.t_user
          key-generator:
            column: user_id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: t_user

    #日志输出
    props:
      sql:
        show: true

  main:
    allow-bean-definition-overriding: true